---
- hosts: PowerEdge
  connection: local
  gather_facts: False
  tasks:
    - name: Get hardware inventory
      dellemc_get_system_inventory:
        idrac_ip: "{{ idrac_ip }}"
        idrac_user: "{{ idrac_user }}"
        idrac_password: "{{ idrac_password }}"
