---
- hosts: PowerEdge
  connection: local
  gather_facts: False
  tasks:
    - name: Retrieve basic inventory of all devices.
      ome_device_info:
        hostname: "{{idrac_ip}}"
        username: "{{idrac_user}}"
        password: "{{idrac_password}}"
